// <auto-generated />
using System;
using FitnessClubApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessClubApi.Migrations
{
    [DbContext(typeof(FitnessClubContext))]
    partial class FitnessClubContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessClubApi.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipCardNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("MembershipCardNumber")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("FitnessClubApi.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("RegistrationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutTypeId");

                    b.HasIndex("ClientId", "WorkoutId")
                        .IsUnique();

                    b.HasIndex("WorkoutId", "WorkoutTypeId");

                    b.HasIndex("SubscriptionId", "ClientId", "WorkoutTypeId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("FitnessClubApi.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RemainingSessions")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("WorkoutTypeId");

                    b.ToTable("Subscriptions", t =>
                        {
                            t.HasCheckConstraint("CK_Subscriptions_Dates", "[EndDate] >= [StartDate]");

                            t.HasCheckConstraint("CK_Subscriptions_Price", "[Price] >= 0");

                            t.HasCheckConstraint("CK_Subscriptions_RemainingSessions_Max", "[RemainingSessions] <= [TotalSessions]");

                            t.HasCheckConstraint("CK_Subscriptions_RemainingSessions_Min", "[RemainingSessions] >= 0");

                            t.HasCheckConstraint("CK_Subscriptions_TotalSessions", "[TotalSessions] > 0");
                        });
                });

            modelBuilder.Entity("FitnessClubApi.Models.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Trainers", t =>
                        {
                            t.HasCheckConstraint("CK_Trainers_ExperienceYears", "[ExperienceYears] >= 0");
                        });
                });

            modelBuilder.Entity("FitnessClubApi.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TrainerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WorkoutDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkoutTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutTypeId");

                    b.HasIndex("TrainerId", "WorkoutDateTime")
                        .IsUnique()
                        .HasFilter("[TrainerId] IS NOT NULL");

                    b.ToTable("Workouts", t =>
                        {
                            t.HasCheckConstraint("CK_Workouts_MaxParticipants", "[MaxParticipants] > 0");
                        });
                });

            modelBuilder.Entity("FitnessClubApi.Models.WorkoutType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequiresTrainer")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("WorkoutTypes", t =>
                        {
                            t.HasCheckConstraint("CK_WorkoutTypes_DurationMinutes", "[DurationMinutes] > 0");
                        });
                });

            modelBuilder.Entity("FitnessClubApi.Models.Registration", b =>
                {
                    b.HasOne("FitnessClubApi.Models.Client", "Client")
                        .WithMany("Registrations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessClubApi.Models.WorkoutType", "WorkoutType")
                        .WithMany("Registrations")
                        .HasForeignKey("WorkoutTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessClubApi.Models.Workout", "Workout")
                        .WithMany("Registrations")
                        .HasForeignKey("WorkoutId", "WorkoutTypeId")
                        .HasPrincipalKey("Id", "WorkoutTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessClubApi.Models.Subscription", "Subscription")
                        .WithMany("Registrations")
                        .HasForeignKey("SubscriptionId", "ClientId", "WorkoutTypeId")
                        .HasPrincipalKey("Id", "ClientId", "WorkoutTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Subscription");

                    b.Navigation("Workout");

                    b.Navigation("WorkoutType");
                });

            modelBuilder.Entity("FitnessClubApi.Models.Subscription", b =>
                {
                    b.HasOne("FitnessClubApi.Models.Client", "Client")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessClubApi.Models.WorkoutType", "WorkoutType")
                        .WithMany("Subscriptions")
                        .HasForeignKey("WorkoutTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("WorkoutType");
                });

            modelBuilder.Entity("FitnessClubApi.Models.Workout", b =>
                {
                    b.HasOne("FitnessClubApi.Models.Trainer", "Trainer")
                        .WithMany("Workouts")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FitnessClubApi.Models.WorkoutType", "WorkoutType")
                        .WithMany("Workouts")
                        .HasForeignKey("WorkoutTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trainer");

                    b.Navigation("WorkoutType");
                });

            modelBuilder.Entity("FitnessClubApi.Models.Client", b =>
                {
                    b.Navigation("Registrations");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("FitnessClubApi.Models.Subscription", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("FitnessClubApi.Models.Trainer", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("FitnessClubApi.Models.Workout", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("FitnessClubApi.Models.WorkoutType", b =>
                {
                    b.Navigation("Registrations");

                    b.Navigation("Subscriptions");

                    b.Navigation("Workouts");
                });
#pragma warning restore 612, 618
        }
    }
}
